### ISSUE TITLE
Asking for password without asking for username

### ISSUE THREAD

**Issue by ShyrenMore** [geekswaroop/OS-Simulator#2]
Hey, I cloned the repo and open the index.html file, but it directly asked for password without asking anything else, is there a common password everybody has to use? if so, kindly put that in readme.md

![image](https://user-images.githubusercontent.com/56788568/121047585-e80b1780-c7d3-11eb-93a8-b3363ac0504c.png)

**Comment by geekswaroop** [comment]
Hey, thanks for the interest in this work.

I believe the password is "OSsimulator". 

Let me know if this doesn't work.
